# Generated by Django 3.1.7 on 2021-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='playlist_name',
            field=models.CharField(max_length=100, verbose_name='Playlist Name'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='url',
            field=models.URLField(),
        ),
    ]
