# Generated by Django 3.1.7 on 2021-04-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20210416_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
